- name: restart_docker
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: docker

- name: restart_kubelet
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: kubelet

- name: sysctl
  ansible.builtin.shell: sysctl --system
