- name: "Removing reference to localhost"
  lineinfile:
    path: /etc/hosts
    line: "127.0.2.1 control control"
    state: absent
    create: true

- name: "Creating control address in /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "192.168.56.10	control"
    state: present
    create: true

- name: "Creating worker1 address in /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "192.168.56.11	worker1"
    state: present
    create: true

- name: "Creating worker2 address in /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "192.168.56.12	worker2"
    state: present
    create: true

