- name: "Adding Kubernetes Repo Key"
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    # => No Checksum?

- name: "Adding Kubernetes Repo"
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
    state: present

- name: "Installing Kubernetes Tools"
  apt:
   pkg: "{{ item }}"
   update-cache: yes
  with_items:
   - kubeadm
   - kubectl
   - kubelet

- name: "Disabeling swap momentarily"
  ansible.builtin.shell: swapoff -a

- name: "Disabeling swap permanetly"
  ansible.builtin.shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

