- name: "Adding Kubernetes Repo Key"
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    # => No Checksum?

- name: "Adding Kubernetes Repo"
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
    state: present

- name: "Installing Kubernetes Tools"
  apt:
   pkg: "{{ item }}"
   update-cache: yes
  with_items:
   - kubeadm
   - kubectl
   - kubelet

- name: "Disabeling swap momentarily"
  ansible.builtin.shell: swapoff -a

- name: "Disabeling swap permanetly"
  ansible.builtin.shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: "Copying kubelet config"
  copy:
    src: ../files/kubelet
    dest: /etc/default/kubelet
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_kubelet

- name: "Copying docker config"
  copy:
    src: ../files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_docker

- name: "Copying 10-kubeadmin.conf"
  copy:
    src: ../files/10-kubeadm.conf
    dest: /usr/lib/systemd/system/kubelet.service.d/10-kubeadmn.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_kubelet

