# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "control" do |control|
    control.vm.box = "bento/ubuntu-24.04"
    control.vm.hostname = "control"

    control.vm.network "private_network", :ip => "192.168.56.10", :adapter => 2


    control.vm.provider "virtualbox" do |v|
      v.memory = 8096
      v.cpus = 2
    end

    control.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/playbook.yml"
    end
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.box = "bento/ubuntu-24.04"
    worker1.vm.hostname = "worker1"

    worker1.vm.network "private_network", :ip => "192.168.56.11", :adapter => 2

    worker1.vm.provider "virtualbox" do |v|
      v.memory = 8096
      v.cpus = 2
    end

    worker1.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/playbook.yml"
    end
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "bento/ubuntu-24.04"
    worker2.vm.hostname = "worker2"

    worker2.vm.network "private_network", :ip => "192.168.56.12", :adapter => 2

    worker2.vm.provider "virtualbox" do |v|
      v.memory = 8096
      v.cpus = 2
    end

    worker2.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/playbook.yml"
    end
  end
end
