# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "control" do |control|
    control.vm.box = "bento/ubuntu-24.04"
    control.vm.hostname = "control"

    config.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/playbook.yml"
    end
  end

  config.vm.define "worker2" do |worker1|
    worker1.vm.box = "bento/ubuntu-24.04"
    worker1.vm.hostname = "worker1"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "bento/ubuntu-24.04"
    worker2.vm.hostname = "worker2"
  end
end
